apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: app-of-apps
  source:
    repoURL: https://github.com/lalitvats1985/argocd-app.git
    targetRevision: master
    path: backend   # 👈 points to backend folder
  destination:
    server: http:// http://34.180.41.88
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
