apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: app-of-apps
  source:
    repoURL: https://github.com/lalitvats1985/argocd-app.git
    targetRevision: master
    path: app-of-apps/frontend   # 👈 points to frontend folder
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
